applications/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", Applications.as_view(), name="index"),
    path("insert", Insert.as_view(), name="insert"),
    path("list", List.as_view(), name="list"),
    path("<int:app_exid>/update", Update.as_view(), name="update"),
    path("<int:app_exid>/details", Details.as_view(), name="details"),
    path("<int:app_exid>/secretKey", SecretKey.as_view(), name="secret-key"),
    path("<int:app_exid>/roles", Roles.as_view(), name="roles"),
    path("<int:app_exid>/domains", Domains.as_view(), name="domains"),
    path("<int:app_exid>/domain/<int:domain_exid>/details", DomainDetails.as_view(), name="domain-details"),
    path("<int:app_exid>/domain/<int:domain_exid>/users", DomainUsers.as_view(), name="domain-users"),
    path("<int:app_exid>/menu/roles", MenuRoles.as_view(), name="menu-roles"),
]

domains/urls.py
from typing import List
from django.urls import path
from .views import *

urlpatterns = [
    path("insert/in/application/<int:app_exid>", AppInsert.as_view(), name="app-insert"),
]

roles/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("insert/in/application/<app_exid>", AppInsert.as_view(), name="app-insert"),
    path("<int:role_exid>/update/in/application/<app_exid>", AppUpdate.as_view(), name="app-update"),
]

systems/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("auth/", include(("authentication.urls", "authentication"), namespace="authentication")),
    path("applications/", include(("applications.urls", "applications"), namespace="applications")),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("roles/", include(("roles.urls", "roles"), namespace="roles")),
    path("domains/", include(("domains.urls", "domains"), namespace="domains")),
]

applications/models.py
from django.db import models

# Create your models here.

domains/models.py
from django.db import models

# Create your models here.

roles/models.py
from django.db import models

# Create your models here.

domains/forms.py
from django import forms

class AppInsert(forms.Form):
    applications    = forms.IntegerField(
        widget      = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "required"      : "required",
                "placeholder"   : "------",
                "readonly"      : "readonly"
            }
        )
    )
    
    name    = forms.CharField(
        widget  = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "required"      : "required",
                "placeholder"   : "------"
            }
        )
    )
    
    url_name    = forms.CharField(
        required    = False,
        widget      = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "placeholder"   : "------"
            }
        )
    )

applications/views.py
from django.shortcuts import render, redirect
from django.http.response import JsonResponse
from django.views.generic.base import View
from django.conf import settings
from django.contrib import messages
from django.utils.html import strip_tags, mark_safe
from datetime import datetime
from systems.cores.middleware import Permission
from systems.engines.apis import Credential
from systems.utilities.messages import ajax_response, errors_to_html
# Forms
from .forms import (
    Insert as FormInsert,
    Update as FormUpdate,
    SecretKey as FormSecretKey,
)

class Applications(View):
    template_name   = "apps/applications/index.html"
    role_can_access = ["superuser"]    
    
    def get(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            context = {
                "HeadTitle" : "Applications",
                "PageTitle" : "Applications"
            }
            return render(request, self.template_name, context)
        else:
            context = {"Message" : user.message}
            return render(request, "errors/401.html", context)
    
class Insert(View):
    template_name   = "apps/applications/includes/insert.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            context = {"FormInsert" : FormInsert}
            return render(request, self.template_name, context)
        else:
            context = {"Message" : user.message}
            return render(request, "errors/401.html", context)
            
    def post(self, request, *args, **kwargs):
        form_insert = FormInsert(request.POST or None)
        if form_insert.is_valid():
            # Api app register
            try:
                token               = request.session.get("token")
                endpoint            = f"data/applications?auth={token}"
                api_app_register    = Credential(endpoint=endpoint, payload=form_insert.cleaned_data).post()
            except Exception as error:
                response    = ajax_response(0, message=error)
                return JsonResponse(response)
            else:
                if api_app_register.is_success():
                    response    = ajax_response(1, message=api_app_register.message, data=api_app_register.data)
                else:
                    response    = ajax_response(0, message=api_app_register.message)
        else:
            errors      = errors_to_html(form_insert.errors)
            response    = ajax_response(0, message=errors)
            
        return JsonResponse(response)
 
class List(View):
    template_name   = "apps/applications/includes/list.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            # Api applications
            try:
                token               = request.session.get("token")
                endpoint            = f"data/applications?auth={token}"
                api_applications    = Credential(endpoint=endpoint).get()
            except Exception as error:
                context = {"Message" : error}
                return render(request, "errors/page-unload.html", context)
            else:
                applications    = api_applications.data if api_applications.is_success() else []
            
            context = {"Applications" : applications}
            return render(request, self.template_name, context)
        else:
            context = {"Message" : user.message}
            return render(request, "errors/page-unload.html", context)
        
class Update(View):
    template_name   = "apps/applications/includes/update.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            # Api application detail
            try:
                app_exid        = kwargs.get("app_exid")
                endpoint        = f"data/application/{app_exid}?auth={token}"
                api_app_detail  = Credential(endpoint=endpoint).get()
            except Exception as error:
                context = {"Message" : error}
                return render(request, "errors/page-unload.html", context)
            else:
                application = api_app_detail.data if api_app_detail.is_success() else []
            
            context = {
                "Application"   : application,
                "FormUpdate"    : FormUpdate(initial=application)
            }
            return render(request, self.template_name, context)
        else:
            context = {"Message" : user.message}
            return render(request, "erros/page-unload.html", context)
        
    def post(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            initial     = {"external_id" : kwargs.get("app_exid")}
            form_update = FormUpdate(request.POST or None, initial=initial)
            if form_update.is_valid():
                # Api application update
                try:
                    app_exid        = form_update.cleaned_data.get("external_id")
                    payload         = form_update.cleaned_data
                    endpoint        = f"data/application/{app_exid}?auth={token}"
                    api_app_update  = Credential(endpoint=endpoint, payload=payload).put()
                except Exception as error:
                    response    = ajax_response(0, message=error)
                    return JsonResponse(response)
                else:
                    if api_app_update.is_success():
                        response    = ajax_response(1, message=api_app_update.message, data=api_app_update.data)
                    else:
                        response    = ajax_response(0, message=api_app_update.message)
            else:
                errors      = errors_to_html(form_update.errors)
                response    = ajax_response(0, message=errors)
        else:
            response    = ajax_response(0, message=user.message)
            
        return JsonResponse(response)
    
class Details(View):
    template_name   = "apps/applications/includes/details.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            # Api application detail
            try:
                app_exid        = kwargs.get("app_exid")
                endpoint        = f"data/application/{app_exid}?auth={token}"
                api_app_detail  = Credential(endpoint=endpoint).get()
            except Exception as error:
                context = {"Message" : error}
                return render(request, "errors/page-unload.html", context)
            else:
                application = api_app_detail.data if api_app_detail.is_success() else []
            
            context = {
                "HeadTitle"     : f"{application.get('shortname')} App",
                "PageTitle"     : f"{application.get('shortname')} App",
                "Application"   : application
            }
            return render(request, self.template_name, context)
        
class SecretKey(View):
    template_name   = "apps/applications/includes/secret_key.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            # Api application secret key
            try:
                app_exid        = kwargs.get("app_exid")
                endpoint        = f"data/application/{app_exid}/secretKey?auth={token}"
                api_app_detail  = Credential(endpoint=endpoint).get()
            except Exception as error:
                context = {"Message" : error}
                return render(request, "errors/page-unload.html", context)
            else:
                application = api_app_detail.data if api_app_detail.is_success() else []
        
            context = {
                "FormSecretKey" : FormSecretKey(initial=application),
                "Application"   : application
            }
            return render(request, self.template_name, context)
        else:
            context = {"Message" : user.message}
            return render(request, "errors/401.html", context)
    
    def post(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            form_secret_key = FormSecretKey(request.POST or None)
            if form_secret_key.is_valid():
                # Api application secret key
                try:
                    app_exid        = form_secret_key.cleaned_data.get("external_id")
                    endpoint        = f"data/application/{app_exid}/secretKey?auth={token}"
                    payload         = form_secret_key.cleaned_data
                    api_app_detail  = Credential(endpoint=endpoint, payload=payload).put()
                except Exception as error:
                    response    = ajax_response(0, message=error)

domains/views.py
from django.shortcuts import render, redirect
from django.http.response import JsonResponse
from django.views.generic.base import View
from django.conf import settings
from django.contrib import messages
from django.utils.html import strip_tags, mark_safe
from datetime import datetime
from systems.cores.middleware import Permission
from systems.engines.apis import Credential
from systems.utilities.messages import ajax_response, errors_to_html
# Forms
from .forms import (
    AppInsert as FormAppInsert
)

class Menu(View):
    template_name   = "apps/domains/includes/menu.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            # Api domains
            try:
                app_exid    = kwargs.get("app_exid")
                endpoint    = f"data/application/{app_exid}/domains?auth={token}"
                api_domains = Credential(endpoint=endpoint).get()
            except Exception as error:
                context = {"Message" : error}
                return render(request, "errors/page-unload.html", context)
            else:
                domains = api_domains.data if api_domains.is_success() else []
            
            context = {"Domains" : domains}
            return render(request, self.template_name, context)
        else:
            context = {"Message" : user.message}
            return render(request, "errors/page-unload.html", context)

class AppInsert(View):
    template_name   = "apps/domains/includes/app_insert.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            initial = {"applications" : kwargs.get("app_exid")}
            context = {
                "ApplicationEXID"   : kwargs.get("app_exid"),
                "FormInsert"        : FormAppInsert(initial=initial),
            }
            return render(request, self.template_name, context)
        else:
            context = {"Message" : user.message}
            return render(request, "errors/401.html", context)
        
    def post(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            initial     = {"applications" : kwargs.get("app_exid")}
            form_insert = FormAppInsert(request.POST or None, initial=initial)
            if form_insert.is_valid():
                try:
                    endpoint            = f"data/domains?auth={token}"
                    payload             = form_insert.cleaned_data
                    api_domain_insert   = Credential(endpoint=endpoint, payload=payload).post()
                except Exception as error:
                    response    = ajax_response(0, message=error)
                    return JsonResponse(response)
                else:
                    if api_domain_insert.is_success():
                        response    = ajax_response(1, message=api_domain_insert.message, data=api_domain_insert.data)
                    else:
                        response    = ajax_response(0, message=api_domain_insert.message)
            else:
                errors      = errors_to_html(form_insert.errors)
                response    = ajax_response(0, message=errors)
        else:
            response    = ajax_response(0, message=user.message)
        
        return JsonResponse(response)
    

templates/apps/applications/includes/domain_users.html
<div class="row mb-3 mt-4">
    <div class="col-xl-3 col-sm-6">
        <div class="mt-2">
            <h5>Users</h5>
        </div>
    </div>
</div>

{% if Users %}
    <div class="row">
        {% for application in Users %}
            <div class="col-sm-3 col-3">
                <div class="card shadow-none border">
                    <div class="card-body p-3">
                        <div class="">
                            <div class="float-end ms-2">
                                <div class="dropdown mb-2">
                                    <a class="font-size-16 text-muted dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="mdi mdi-dots-horizontal"></i>
                                    </a>
                                    
                                    <div class="dropdown-menu dropdown-menu-end" style="">
                                        <a class="dropdown-item" href="{% url 'applications:details' app_exid=application.external_id %}">Open</a>
                                        <a 
                                            class="dropdown-item btn-show-modal-application-update"
                                            href="javascript:void(0)"
                                            data-namespace="{% url 'applications:update' app_exid=application.external_id %}"
                                        >
                                            Edit
                                        </a>
                                        <div class="dropdown-divider"></div>
                                        {% if application.is_archived %}
                                            <a class="dropdown-item text-success" href="#">Restore</a>
                                        {% else %}
                                            <a class="dropdown-item text-danger" href="#">Archived</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
    
                            <div class="avatar-xs me-3 mb-3">
                                <div class="avatar-title bg-transparent rounded">
                                    <i class="bx bxs-folder font-size-24 text-warning"></i>
                                </div>
                            </div>
                            
                            <div class="d-flex">
                                <div class="overflow-hidden me-auto">
                                    <h5 class="font-size-14 text-truncate mb-1"><a href="javascript: void(0);" class="text-body">{{ application.shortname|upper }}</a></h5>
                                    <p class="text-muted text-truncate mb-0">{{ application.description|title }}</p>
                                </div>
                                
                                <div class="align-self-end ms-2">
                                    {% if application.is_archived %}
                                        <p class="text-muted mb-0">
                                            <i class="bx bxs-album font-size-18 align-middle text-danger me-2"></i>
                                        </p>
                                    {% else %}
                                        <p class="text-muted mb-0">
                                            <i class="bx bxs-album font-size-18 align-middle text-success me-2"></i>
                                        </p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <div class="bg-warning bg-soft p-3 rounded mb-3">
        <h5 class="font-size-14 text-primary mb-0"><i class="fas fa-exclamation-triangle  me-2"></i>
            <strong>No data found</strong>
        </h5>
    </div>
{% endif %}

templates/apps/applications/includes/domains.html
<div class="row mb-3 mt-4">
    <div class="col-xl-3 col-sm-6">
        <div class="mt-2">
            <h5>Domains</h5>
        </div>
    </div>
</div>

<div class="row">
    {% if Domains %}
        {% for domain in Domains %}
            <div class="col-xl-4 col-sm-6">
                <div class="card shadow-none border">
                    <div class="card-body p-3">
                        <div class="">
                            <div class="float-end ms-2">
                                <div class="dropdown mb-2">
                                    <a class="font-size-16 text-muted dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true">
                                        <i class="mdi mdi-dots-horizontal"></i>
                                    </a>
                                    
                                    <div class="dropdown-menu dropdown-menu-end">
                                        <a class="dropdown-item" href="{% url 'applications:domain-details' domain_exid=domain.external_id app_exid=ApplicationEXID %}">Open</a>
                                        <a class="dropdown-item" href="#">Edit</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item text-danger" href="#">Archived</a>
                                    </div>
                                </div>
                            </div>

                            <div class="avatar-xs me-3 mb-3">
                                <div class="avatar-title bg-transparent rounded">
                                    <i class="bx bxs-folder font-size-24 text-warning"></i>
                                </div>
                            </div>
                            
                            <div class="d-flex">
                                <div class="overflow-hidden me-auto">
                                    <h5 class="font-size-14 text-truncate mb-1"><a href="javascript: void(0);" class="text-body">{{ domain.name|upper }}</a></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="bg-warning bg-soft p-3 rounded mb-3">
            <h5 class="font-size-14 text-primary mb-0"><i class="fas fa-exclamation-triangle  me-2"></i>
                <strong>No data found</strong>
            </h5>
        </div>
    {% endif %}
</div>

templates/apps/applications/includes/insert.html
{% load static %}

<div class="bg-warning bg-soft p-3 rounded mb-3">
    <h5 class="font-size-14 text-primary mb-0"><i class="fas fa-exclamation-triangle  me-2"></i>
        All fields are required, except marked <strong><i>*optional</i></strong>
    </h5>
</div>

<div id="message"></div>

<form class="custom-validation" id="form-application-insert">
    {% csrf_token %}

    <div class="col-md-12">
        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Application Host</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>
            {{ FormInsert.host }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Application Shortname</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>
            {{ FormInsert.shortname }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Email</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>
            {{ FormInsert.email }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Description</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>
            {{ FormInsert.description }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
    </div>

    <button class="btn btn-lg btn-outline-success waves-effect waves-light btn-save" type="submit">
        Save
    </button>
</form>

<!-- Form validation -->
<script src="{% static 'assets/libs/parsleyjs/parsley.min.js' %}"></script>
<script src="{% static 'assets/js/pages/form-validation.init.js' %}"></script>

<script src="{% static 'assets/libs/select2/js/select2.min.js' %}"></script>

<script>
    xpost(
        "form-application-insert",
        "{% url 'applications:insert' %}",
        function(response) {
            if (response.is_success) {
                console.log(response.message)
                xload("ajax-list", "{% url 'applications:list' %}")
                // xload("menu", "")
                message = alert_message("success", "Message", response.message, "<br /> Application saved")
            } else {
                console.log(response.message)
                message = alert_message("danger", "Whoops", response.message)
            }
            $("#message").html(message)
        }
    )
</script>

templates/apps/applications/includes/list.html
{% if Applications %}
    <div class="row">
        {% for application in Applications %}
            <div class="col-sm-3 col-3">
                <div class="card shadow-none border">
                    <div class="card-body p-3">
                        <div class="">
                            <div class="float-end ms-2">
                                <div class="dropdown mb-2">
                                    <a class="font-size-16 text-muted dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="mdi mdi-dots-horizontal"></i>
                                    </a>
                                    
                                    <div class="dropdown-menu dropdown-menu-end" style="">
                                        <a class="dropdown-item" href="{% url 'applications:details' app_exid=application.external_id %}">Open</a>
                                        <a 
                                            class="dropdown-item btn-show-modal-application-update"
                                            href="javascript:void(0)"
                                            data-namespace="{% url 'applications:update' app_exid=application.external_id %}"
                                        >
                                            Edit
                                        </a>
                                        <div class="dropdown-divider"></div>
                                        {% if application.is_archived %}
                                            <a class="dropdown-item text-success" href="#">Restore</a>
                                        {% else %}
                                            <a class="dropdown-item text-danger" href="#">Archived</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
    
                            <div class="avatar-xs me-3 mb-3">
                                <div class="avatar-title bg-transparent rounded">
                                    <i class="bx bxs-folder font-size-24 text-warning"></i>
                                </div>
                            </div>
                            
                            <div class="d-flex">
                                <div class="overflow-hidden me-auto">
                                    <h5 class="font-size-14 text-truncate mb-1"><a href="javascript: void(0);" class="text-body">{{ application.shortname|upper }}</a></h5>
                                    <p class="text-muted text-truncate mb-0">{{ application.description|title }}</p>
                                </div>
                                
                                <div class="align-self-end ms-2">
                                    {% if application.is_archived %}
                                        <p class="text-muted mb-0">
                                            <i class="bx bxs-album font-size-18 align-middle text-danger me-2"></i>
                                        </p>
                                    {% else %}
                                        <p class="text-muted mb-0">
                                            <i class="bx bxs-album font-size-18 align-middle text-success me-2"></i>
                                        </p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <div class="bg-warning bg-soft p-3 rounded mb-3">
        <h5 class="font-size-14 text-primary mb-0"><i class="fas fa-exclamation-triangle  me-2"></i>
            <strong>No data found</strong>
        </h5>
    </div>
{% endif %}

templates/apps/applications/includes/menu_roles.html
{% if Roles %}
    {% for role in Roles %}
        <li>
            <a href="#" class="d-flex align-items-center">
                <span class="me-auto">
                    {{ role.name|title }}
                </span>
            </a>
        </li>
    {% endfor %}
{% else %}
    <li>
        <a href="javascript:void(0)" class="d-flex align-items-center">
            <span class="me-auto">
                <strong>
                    <i>No data found</i>
                </strong>
            </span>
        </a>
    </li>
{% endif %}