applications/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", Applications.as_view(), name="index"),
    path("insert", Insert.as_view(), name="insert"),
    path("list", List.as_view(), name="list"),
    path("<int:app_exid>/update", Update.as_view(), name="update"),
    path("<int:app_exid>/details", Details.as_view(), name="details"),
    path("<int:app_exid>/secretKey", SecretKey.as_view(), name="secret-key"),
    path("<int:app_exid>/roles", Roles.as_view(), name="roles"),
    path("<int:app_exid>/domains", Domains.as_view(), name="domains"),
    path("<int:app_exid>/domain/<int:domain_exid>/details", DomainDetails.as_view(), name="domain-details"),
    path("<int:app_exid>/domain/<int:domain_exid>/users", DomainUsers.as_view(), name="domain-users"),
    path("<int:app_exid>/menu/roles", MenuRoles.as_view(), name="menu-roles"),
]

roles/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("insert/in/application/<app_exid>", AppInsert.as_view(), name="app-insert"),
    path("<int:role_exid>/update/in/application/<app_exid>", AppUpdate.as_view(), name="app-update"),
]

systems/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("auth/", include(("authentication.urls", "authentication"), namespace="authentication")),
    path("applications/", include(("applications.urls", "applications"), namespace="applications")),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("roles/", include(("roles.urls", "roles"), namespace="roles")),
    path("domains/", include(("domains.urls", "domains"), namespace="domains")),
]

templates/general/footer.html
        {% load static %}

        <!-- Modals -->
        <!-- Modal coming soon -->
        <div class="modal fade modal-coming-soon" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Whoops</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="text-center">
                                    <!-- <a href="index.html" class="d-block auth-logo">
                                        <img src="assets/images/logo-dark.png" alt="" height="20" class="auth-logo-dark mx-auto">
                                        <img src="assets/images/logo-light.png" alt="" height="20" class="auth-logo-light mx-auto">
                                    </a> -->
                                    <div class="row justify-content-center mt-5">
                                        <div class="col-sm-4">
                                            <div class="maintenance-img">
                                                <img src="{% static 'assets/images/coming-soon.svg' %}" alt="" class="img-fluid mx-auto d-block">
                                            </div>
                                        </div>
                                    </div>
                                    <h4 class="mt-5">Let's get started with Clight</h4>
                                    <p class="text-muted">It will be as simple as Occidental in fact it will be Occidental.</p>
            
                                    <div class="row justify-content-center mt-5">
                                        <div class="col-md-8">
                                            <div data-countdown="2021/12/31" class="counter-number"></div>
                                        </div> <!-- end col-->
                                    </div> <!-- end row-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- JAVASCRIPT -->
        <script src="{% static 'assets/libs/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'assets/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets/libs/metismenu/metisMenu.min.js' %}"></script>
        <script src="{% static 'assets/libs/simplebar/simplebar.min.js' %}"></script>
        <script src="{% static 'assets/libs/node-waves/waves.min.js' %}"></script>
        <script src="{% static 'assets/js/app.js' %}"></script>
        <script src="{% static 'assets/js/custom.js' %}"></script>

        <script src="{% static 'assets/libs/select2/js/select2.min.js' %}"></script>
        <script src="{% static 'assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
        <script src="{% static 'assets/libs/spectrum-colorpicker2/spectrum.min.js' %}"></script>
        <script src="{% static 'assets/libs/bootstrap-timepicker/js/bootstrap-timepicker.min.js' %}"></script>
        <script src="{% static 'assets/libs/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js' %}"></script>
        <script src="{% static 'assets/libs/bootstrap-maxlength/bootstrap-maxlength.min.js' %}"></script>
        <script src="{% static 'assets/libs/%40chenfengyuan/datepicker/datepicker.min.js' %}"></script>

        <!-- Form validation -->
        <script src="{% static 'assets/libs/parsleyjs/parsley.min.js' %}"></script>
        <script src="{% static 'assets/js/pages/form-validation.init.js' %}"></script>

        <!-- Required datatable js -->
        <script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
        
        <!-- Buttons examples -->
        <script src="{% static 'assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
        <script src="{% static 'assets/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
        <script src="{% static 'assets/libs/jszip/jszip.min.js' %}"></script>
        <script src="{% static 'assets/libs/pdfmake/build/pdfmake.min.js' %}"></script>
        <script src="{% static 'assets/libs/pdfmake/build/vfs_fonts.js' %}"></script>
        <script src="{% static 'assets/libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
        <script src="{% static 'assets/libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
        <script src="{% static 'assets/libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>

        <!-- Responsive examples -->
        <script src="{% static 'assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'assets/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

        <!-- Datatable init js -->
        <script src="{% static 'assets/js/pages/datatables.init.js' %}"></script>

        <!-- Plugins js -->
        <script src="{% static 'assets/libs/dropzone/min/dropzone.min.js' %}"></script>
        
        <!-- Magnific Popup-->
        <script src="{% static 'assets/libs/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

        <!-- lightbox init js-->
        <script src="{% static 'assets/js/pages/lightbox.init.js' %}"></script>

        <!-- Dropify -->
        <script src="{% static 'plugins/dropify/js/dropify.min.js' %}"></script>

        <!-- Responsive Table js -->
        <script src="{% static 'assets/libs/admin-resources/rwd-table/rwd-table.min.js' %}"></script>

        <!-- Init js -->
        <script src="{% static 'assets/js/pages/table-responsive.init.js' %}"></script>

        <script>
            // Get menu
            
        </script>
    </body>

templates/general/menu.html
<div class="vertical-menu">
    <div data-simplebar class="h-100">
        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title" key="t-apps">Main</li>

                <!-- <li>
                    <a href="javascript: void(0);" class="waves-effect">
                        <i class="bx bx-message-square"></i>
                        <span key="t-dashboards">Dashboard</span>
                    </a>
                </li> -->

                <li>
                    <a href="{% url 'applications:index' %}" class="waves-effect">
                        <i class="bx bx-table "></i>
                        <span key="t-dashboards">Applications</span>
                    </a>

                    <!-- <ul class="sub-menu" aria-expanded="false">
                        <li><a href="javascript:void(0)" key="t-categories">Categories</a></li>
                        <li><a href="javascript:void(0)" key="t-foundsSource">Funds Source</a></li>
                        <li><a href="javascript:void(0)" key="t-transactoions">Transactions</a></li>
                    </ul> -->
                </li>

                <li class="menu-title" key="t-apps">Settings</li>

                <li>
                    <a href="javascript: void(0);" class="waves-effect">
                        <i class="bx bx-message-square"></i>
                        <span key="t-dashboards">User Management</span>
                    </a>
                </li>

                <li>
                    <a href="javascript: void(0);" class="waves-effect">
                        <i class="bx bx-message-square"></i>
                        <span key="t-dashboards">My Profile</span>
                    </a>
                </li>

                <li>
                    <a href="javascript: void(0);" class="waves-effect">
                        <i class="bx bx-message-square"></i>
                        <span key="t-dashboards">About Us</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/general/offcanvas.html
<!-- Offcanvas -->
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvas-application-details" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h5 id="offcanvasRightLabel"></h5>
        <button type="button" class="btn-close text-reset offcanvas-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>

    <div class="offcanvas-body">
        <div id="ajax-offcanvas-body"></div>
    </div>
</div>