applications/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", Applications.as_view(), name="index"),
    path("insert", Insert.as_view(), name="insert"),
    path("list", List.as_view(), name="list"),
    path("<int:app_exid>/update", Update.as_view(), name="update"),
    path("<int:app_exid>/details", Details.as_view(), name="details"),
    path("<int:app_exid>/secretKey", SecretKey.as_view(), name="secret-key"),
    path("<int:app_exid>/roles", Roles.as_view(), name="roles"),
    path("<int:app_exid>/domains", Domains.as_view(), name="domains"),
    path("<int:app_exid>/domain/<int:domain_exid>/details", DomainDetails.as_view(), name="domain-details"),
    path("<int:app_exid>/domain/<int:domain_exid>/users", DomainUsers.as_view(), name="domain-users"),
    path("<int:app_exid>/menu/roles", MenuRoles.as_view(), name="menu-roles"),
]

roles/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("insert/in/application/<app_exid>", AppInsert.as_view(), name="app-insert"),
    path("<int:role_exid>/update/in/application/<app_exid>", AppUpdate.as_view(), name="app-update"),
]

systems/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("auth/", include(("authentication.urls", "authentication"), namespace="authentication")),
    path("applications/", include(("applications.urls", "applications"), namespace="applications")),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("roles/", include(("roles.urls", "roles"), namespace="roles")),
    path("domains/", include(("domains.urls", "domains"), namespace="domains")),
]

roles/models.py
from django.db import models

# Create your models here.

roles/forms.py
from django import forms

class AppInsert(forms.Form):
    application     = forms.IntegerField(
        widget      = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "required"      : "required",
                "placeholder"   : "------",
                "readonly"      : "readonly"
            }
        )
    )
    
    name    = forms.CharField(
        widget  = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "required"      : "required",
                "placeholder"   : "------"
            }
        )
    )
    
class AppUpdate(forms.Form):
    external_id     = forms.IntegerField(
        required    = True,
        widget      = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "required"      : "required",
                "placeholder"   : "------",
                "readonly"      : "readonly"
            }
        )
    )
    
    application     = forms.IntegerField(
        required    = True,
        widget      = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "required"      : "required",
                "placeholder"   : "------",
                "readonly"      : "readonly"
            }
        )
    )
    
    name    = forms.CharField(
        widget  = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "required"      : "required",
                "placeholder"   : "------"
            }
        )
    )

roles/views.py
from os import O_ASYNC
from time import strptime
from urllib import response
from django.shortcuts import render, redirect
from django.http.response import JsonResponse
from django.views.generic.base import View
from django.conf import settings
from django.contrib import messages
from django.utils.html import strip_tags, mark_safe
from datetime import datetime
from systems.cores.middleware import Permission
from systems.engines.apis import Credential
from systems.utilities.messages import ajax_response, errors_to_html
# Forms
from .forms import (
    AppInsert as FormAppInsert,
    AppUpdate as FormAppUpdate,
)

class AppInsert(View):
    template_name   = "apps/roles/includes/app_insert.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token       = request.session.get("token")
        user        = Permission(token=token, role_can_access=self.role_can_access)
        app_exid    = kwargs.get("app_exid")
        if user.granted_permission():
            initial = {"application" : app_exid}
            context = {
                "FormInsert"        : FormAppInsert(initial=initial),
                "ApplicationEXID"   : kwargs.get("app_exid")
            }
            return render(request, self.template_name, context)
        else:
            context = {"Message" : user.message}
            return render(request, "errors/unload-page.html", context)
    
    def post(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            form_insert = FormAppInsert(request.POST or None)
            if form_insert.is_valid():
                # Api role
                try:
                    endpoint    = f"data/roles?auth={token}"
                    payload     = form_insert.cleaned_data
                    api_role    = Credential(endpoint=endpoint, payload=payload).post()
                except Exception as error:
                    response    = ajax_response(0, error)
                    return JsonResponse(response)
                else:
                    if api_role.is_success():
                        response    = ajax_response(1, message=api_role.message, data=api_role.data)
                    else:
                        response    = ajax_response(0, message=api_role.message)
            else:
                errors      = errors_to_html(form_insert.errors)
                response    = ajax_response(0, message=errors)
        else:
            response    = ajax_response(0, message=user.message)
            
        return JsonResponse(response)

class AppUpdate(View):
    template_name   = "apps/roles/includes/update.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token       = request.session.get("token")
        user        = Permission(token=token, role_can_access=self.role_can_access)
        app_exid    = kwargs.get("app_exid")
        role_exid   = kwargs.get("role_exid")
        if user.granted_permission():
            # Api role detail
            try:
                endpoint        = f"data/roles/{role_exid}?auth={token}"
                api_role_detail = Credential(endpoint=endpoint).get()
            except Exception as error:
                context = {"Message" : error}
                return render(request, "errors/page-unload.html", context)
            else:
                role    = api_role_detail.data if api_role_detail.is_success() else []
            
            initial                 = role
            initial["application"]  = app_exid
            context                 = {
                "RoleEXID"          : role.get("external_id"),
                "ApplicationEXID"   : kwargs.get("app_exid"),
                "FormUpdate"        : FormAppUpdate(initial=role)
            }
            return render(request, self.template_name, context)
        
    def post(self, request, *args, **kwargs):
        token       = request.session.get("token")
        user        = Permission(token=token, role_can_access=self.role_can_access)
        role_exid   = kwargs.get("role_exid")
        app_exid    = kwargs.get("app_exid")
        if user.granted_permission():
            initial     = {
                "external_id"   : role_exid,
                "application"   : app_exid
            }
            form_update = FormAppUpdate(request.POST or None, initial=initial)
            if form_update.is_valid():
                # Api role update
                try:
                    role_exid       = form_update.cleaned_data.get("external_id")
                    payload         = form_update.cleaned_data
                    endpoint        = f"data/roles/{role_exid}?auth={token}"
                    api_role_update = Credential(endpoint=endpoint, payload=payload).put()
                except Exception as error:
                    response    = ajax_response(0, message=error)
                    return JsonResponse(response)
                else:
                    if api_role_update.is_success():
                        response    = ajax_response(1, message=api_role_update.message, data=api_role_update.data)
                    else:
                        response    = ajax_response(0, message=api_role_update.message)
            else:
                errors      = errors_to_html(form_update.errors)
                response    = ajax_response(0, message=errors)
        else:
            response    = ajax_response(0, message=user.message)
            
        return JsonResponse(response)

templates/apps/roles/includes/app_insert.html
{% load static %}

<div class="bg-warning bg-soft p-3 rounded mb-3">
    <h5 class="font-size-14 text-primary mb-0"><i class="fas fa-exclamation-triangle  me-2"></i>
        All fields are required, except marked <strong><i>*optional</i></strong>
    </h5>
</div>

<div id="message-role"></div>

<form class="custom-validation" id="form-role-insert">
    {% csrf_token %}

    <div class="col-md-12">
        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Application</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>

            {{ FormInsert.application }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>

        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Role Name</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>

            {{ FormInsert.name }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
    </div>

    <button class="btn btn-lg btn-outline-success waves-effect waves-light btn-save" type="submit">
        Save
    </button>
</form>

<!-- Form validation -->
<script src="{% static 'assets/libs/parsleyjs/parsley.min.js' %}"></script>
<script src="{% static 'assets/js/pages/form-validation.init.js' %}"></script>

<script src="{% static 'assets/libs/select2/js/select2.min.js' %}"></script>

<script>
    xpost(
        "form-role-insert",
        "{% url 'roles:app-insert' app_exid=ApplicationEXID %}",
        function(response) {
            if (response.is_success) {
                console.log(response.message)
                xload("ajax-application-roles", "{% url 'applications:roles' app_exid=ApplicationEXID %}")
                xload("ajax-application-roles-menu", "{% url 'applications:menu-roles' app_exid=ApplicationEXID %}")
                message = alert_message("success", "Message", response.message, "<br /> role saved")
            } else {
                console.log(response.message)
                message = alert_message("danger", "Whoops", response.message)
            }
            $("#message-role").html(message)
        }
    )
</script>

templates/apps/roles/includes/update.html
{% load static %}

<div class="bg-warning bg-soft p-3 rounded mb-3">
    <h5 class="font-size-14 text-primary mb-0"><i class="fas fa-exclamation-triangle  me-2"></i>
        All fields are required, except marked <strong><i>*optional</i></strong>
    </h5>
</div>

<div id="message-role-update"></div>

<form class="custom-validation" id="form-role-insert">
    {% csrf_token %}

    <div class="col-md-12">
        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Role ID</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>

            {{ FormUpdate.external_id }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>

        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Application ID</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>

            {{ FormUpdate.application }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>

        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Role Name</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>

            {{ FormUpdate.name }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
    </div>

    <button class="btn btn-lg btn-outline-success waves-effect waves-light btn-save" type="submit">
        Save
    </button>
</form>

<!-- Form validation -->
<script src="{% static 'assets/libs/parsleyjs/parsley.min.js' %}"></script>
<script src="{% static 'assets/js/pages/form-validation.init.js' %}"></script>

<script src="{% static 'assets/libs/select2/js/select2.min.js' %}"></script>

<script>
    xpost(
        "form-role-insert",
        "{% url 'roles:app-update' role_exid=RoleEXID app_exid=ApplicationEXID %}",
        function(response) {
            if (response.is_success) {
                console.log(response.message)
                xload("ajax-application-roles", "{% url 'applications:roles' app_exid=ApplicationEXID %}")
                xload("ajax-application-roles-menu", "{% url 'applications:menu-roles' app_exid=ApplicationEXID %}")
                message = alert_message("success", "Message", response.message, "<br /> role saved")
            } else {
                console.log(response.message)
                message = alert_message("danger", "Whoops", response.message)
            }
            $("#message-role-update").html(message)
        }
    )
</script>