applications/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", Applications.as_view(), name="index"),
    path("insert", Insert.as_view(), name="insert"),
    path("list", List.as_view(), name="list"),
    path("<int:app_exid>/update", Update.as_view(), name="update"),
    path("<int:app_exid>/details", Details.as_view(), name="details"),
    path("<int:app_exid>/secretKey", SecretKey.as_view(), name="secret-key"),
    path("<int:app_exid>/roles", Roles.as_view(), name="roles"),
    path("<int:app_exid>/domains", Domains.as_view(), name="domains"),
    path("<int:app_exid>/domain/<int:domain_exid>/details", DomainDetails.as_view(), name="domain-details"),
    path("<int:app_exid>/domain/<int:domain_exid>/users", DomainUsers.as_view(), name="domain-users"),
    path("<int:app_exid>/menu/roles", MenuRoles.as_view(), name="menu-roles"),
]

domains/urls.py
from typing import List
from django.urls import path
from .views import *

urlpatterns = [
    path("insert/in/application/<int:app_exid>", AppInsert.as_view(), name="app-insert"),
]

roles/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("insert/in/application/<app_exid>", AppInsert.as_view(), name="app-insert"),
    path("<int:role_exid>/update/in/application/<app_exid>", AppUpdate.as_view(), name="app-update"),
]

systems/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("auth/", include(("authentication.urls", "authentication"), namespace="authentication")),
    path("applications/", include(("applications.urls", "applications"), namespace="applications")),
    path("users/", include(("users.urls", "users"), namespace="users")),
    path("roles/", include(("roles.urls", "roles"), namespace="roles")),
    path("domains/", include(("domains.urls", "domains"), namespace="domains")),
]

domains/models.py
from django.db import models

# Create your models here.

domains/forms.py
from django import forms

class AppInsert(forms.Form):
    applications    = forms.IntegerField(
        widget      = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "required"      : "required",
                "placeholder"   : "------",
                "readonly"      : "readonly"
            }
        )
    )
    
    name    = forms.CharField(
        widget  = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "required"      : "required",
                "placeholder"   : "------"
            }
        )
    )
    
    url_name    = forms.CharField(
        required    = False,
        widget      = forms.TextInput(
            attrs   = {
                "class"         : "form-control",
                "placeholder"   : "------"
            }
        )
    )

domains/views.py
from django.shortcuts import render, redirect
from django.http.response import JsonResponse
from django.views.generic.base import View
from django.conf import settings
from django.contrib import messages
from django.utils.html import strip_tags, mark_safe
from datetime import datetime
from systems.cores.middleware import Permission
from systems.engines.apis import Credential
from systems.utilities.messages import ajax_response, errors_to_html
# Forms
from .forms import (
    AppInsert as FormAppInsert
)

class Menu(View):
    template_name   = "apps/domains/includes/menu.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            # Api domains
            try:
                app_exid    = kwargs.get("app_exid")
                endpoint    = f"data/application/{app_exid}/domains?auth={token}"
                api_domains = Credential(endpoint=endpoint).get()
            except Exception as error:
                context = {"Message" : error}
                return render(request, "errors/page-unload.html", context)
            else:
                domains = api_domains.data if api_domains.is_success() else []
            
            context = {"Domains" : domains}
            return render(request, self.template_name, context)
        else:
            context = {"Message" : user.message}
            return render(request, "errors/page-unload.html", context)

class AppInsert(View):
    template_name   = "apps/domains/includes/app_insert.html"
    role_can_access = ["superuser"]
    
    def get(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            initial = {"applications" : kwargs.get("app_exid")}
            context = {
                "ApplicationEXID"   : kwargs.get("app_exid"),
                "FormInsert"        : FormAppInsert(initial=initial),
            }
            return render(request, self.template_name, context)
        else:
            context = {"Message" : user.message}
            return render(request, "errors/401.html", context)
        
    def post(self, request, *args, **kwargs):
        token   = request.session.get("token")
        user    = Permission(token=token, role_can_access=self.role_can_access)
        if user.granted_permission():
            initial     = {"applications" : kwargs.get("app_exid")}
            form_insert = FormAppInsert(request.POST or None, initial=initial)
            if form_insert.is_valid():
                try:
                    endpoint            = f"data/domains?auth={token}"
                    payload             = form_insert.cleaned_data
                    api_domain_insert   = Credential(endpoint=endpoint, payload=payload).post()
                except Exception as error:
                    response    = ajax_response(0, message=error)
                    return JsonResponse(response)
                else:
                    if api_domain_insert.is_success():
                        response    = ajax_response(1, message=api_domain_insert.message, data=api_domain_insert.data)
                    else:
                        response    = ajax_response(0, message=api_domain_insert.message)
            else:
                errors      = errors_to_html(form_insert.errors)
                response    = ajax_response(0, message=errors)
        else:
            response    = ajax_response(0, message=user.message)
        
        return JsonResponse(response)
    

templates/apps/domains/includes/app_insert.html
{% load static %}

<div class="bg-warning bg-soft p-3 rounded mb-3">
    <h5 class="font-size-14 text-primary mb-0"><i class="fas fa-exclamation-triangle  me-2"></i>
        All fields are required, except marked <strong><i>*optional</i></strong>
    </h5>
</div>

<div id="message"></div>

<form class="custom-validation" id="form-domain-insert">
    {% csrf_token %}

    <div class="col-md-12">
        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Application ID</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>
            {{ FormInsert.applications }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>

        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Domain Name</label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>
            {{ FormInsert.name }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>

        <div class="mb-4">
            <label for="validationCustom01" class="form-label">Domain URL Name <strong><i>*optional</i></strong></label>
            <p class="text-muted">
                Please note: if the <code>alwaysShow</code> option is enabled, the
                <code>threshold</code> option is ignored.
            </p>
            {{ FormInsert.url_name }}
            <div class="valid-feedback">
                Looks good!
            </div>
        </div>
    </div>

    <button class="btn btn-lg btn-outline-success waves-effect waves-light btn-save" type="submit">
        Save
    </button>
</form>

<!-- Form validation -->
<script src="{% static 'assets/libs/parsleyjs/parsley.min.js' %}"></script>
<script src="{% static 'assets/js/pages/form-validation.init.js' %}"></script>

<script src="{% static 'assets/libs/select2/js/select2.min.js' %}"></script>

<script>
    xpost(
        "form-domain-insert",
        "{% url 'domains:app-insert' app_exid=ApplicationEXID %}",
        function(response) {
            if (response.is_success) {
                console.log(response.message)
                xload("ajax-application-domains", "{% url 'applications:domains' app_exid=ApplicationEXID %}")
                message = alert_message("success", "Message", response.message, "<br /> Domain saved")
            } else {
                console.log(response.message)
                message = alert_message("danger", "Whoops", response.message)
            }
            $("#message").html(message)
        }
    )
</script>

templates/apps/domains/includes/menu.html
{% if Domains %}
    {% for domain in Domains %}
        <li>
            <a href="#" class="d-flex align-items-center">
                <span class="me-auto">
                    {{ domain.name|upper }}
                </span>
            </a>
        </li>
    {% endfor %}
{% else %}
    <li>
        <a href="javascript:void(0)" class="d-flex align-items-center">
            <span class="me-auto">
                <strong>
                    <i>No data found</i>
                </strong>
            </span>
        </a>
    </li>
{% endif %}